# Generated by Django 5.1 on 2024-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('bookType', models.CharField(max_length=10)),
            ],
        ),
    ]
