# Generated by Django 5.1 on 2024-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stevestuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='row',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
