# Generated by Django 5.1 on 2024-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stevestuff', '0002_book_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='row',
            field=models.IntegerField(),
        ),
    ]
